name: backend
description: SpotIT Backend utilities and scripts
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: any
  firebase_core: any
  geoflutterfire_plus: any
  http: ^1.2.0
